### ISSUE TITLE
Criar classes serviço e agendamento

### ISSUE THREAD

**Issue by wemersonifpe** [ifpe-cti/petpalacy#15]
criação da classe agendamento que contem data e serviços escolhidos pelo cliente, criação da classe serviço que e atributo da classe agendamento.

**Comment by Kaio-Brasil** [comment]
Na classe serviço tem um atributo de duração.
A minha duvida é! O serviço é cobrado pelo serviço prestado ou pelo tempo de duração, tem como explicar isso?
