### ISSUE TITLE
Criação da conexão com o banco de dados e classes DAO

### ISSUE THREAD

**Issue by Kaio-Brasil** [ifpe-cti/petpalacy#26]
Conexão com o banco de dados com MySQL, usando o framework Hibernate 5. Criação das classes dao e dao generico mais classe de persistencia.

**Comment by DanielCalado** [comment]
@Kaio-Brasil, quando você pode enviar sua parte?
lembre-se que a breach que você vai abrir tem que ter o numero dessa issue #26.
So nos veremos no if terça feira então e viável que você envie antes.

**Comment by Kaio-Brasil** [comment]
@DanielCalado Soluções de erros e envio de classe que estavam faltando.
