### ISSUE TITLE
Escolha das telas 

### ISSUE THREAD

**Issue by DanielCalado** [ifpe-cti/petpalacy#90]
@izaquiel7, @wemersonifpe e @Kaio-Brasil. Escolham a issue das telas que querem fazer

**Comment by izaquiel7** [comment]
@DanielCalado, eu fico co as telas sobre Empresa issue #87

**Comment by izaquiel7** [comment]
@DanielCalado essas telas incluem logar, não é?

**Comment by DanielCalado** [comment]
@izaquiel7, Sim

**Comment by DanielCalado** [comment]
@izaquiel7, @Kaio-Brasil. 
@wemersonifpe ta sem Internet des do dia 27/05 entao nao pode escolher as telas.

**Comment by DanielCalado** [comment]
@izaquiel7, e ai ja tem alguma tela feita?

**Comment by DanielCalado** [comment]
@Kaio-Brasil. E ai vai escolher as telas que vai fazer?

**Comment by DanielCalado** [comment]
@izaquiel7, @Kaio-Brasil. As aulas voltarão seg, ate foco so nas telas, passei esses últimos dias fazendo correções no código e so vou fazer o pr com o ok de vilmar.
